### ISSUE TITLE
Parsing semicolons

### ISSUE THREAD

**Issue by Vanuan** [openownership/ua-edr-extractor#4]
It looks like semicolons aren't properly recognized:

https://register.openownership.org/entities/5a7b06a89dfc3fae184e6996

**Comment by Vanuan** [comment]
Probably should add limited to stop words?

**Comment by Vanuan** [comment]
Should be fixed by #5

**Comment by dchaplinsky** [comment]
Don't expect quick update of the data in OO tho.
